#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""wordpress-mdx-next one-click release script.

Usage:
    python scripts/release.py 3.0.0            # bump versions, commit, tag
    python scripts/release.py 3.0.0 --push     # same, then push to origin (with tag)

What it does:
    1. style.css                 -> Version header
    2. includes/admin_init_ver.php -> mdx_version / mdx_version_commit (version + short hash)
    3. includes/cdn_version.php  -> jsDelivr CDN pinned commit (current HEAD)
    4. info.json                 -> update-checker metadata (version + tag zip url)
    5. git commit + git tag v<version>
    6. optional: push origin main + tag

Run this AFTER committing all feature/asset changes: the CDN pin takes the
current HEAD, so it must already include every static-file change of the release.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")


def run_git(*args, check=True):
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        check=check, capture_output=True, text=True, encoding="utf-8",
    ).stdout.strip()


def main():
    argv = [a for a in sys.argv[1:] if a != "--push"]
    do_push = "--push" in sys.argv[1:]
    if len(argv) != 1 or not VERSION_RE.match(argv[0]):
        sys.exit("usage: python scripts/release.py <x.y.z> [--push]")
    version = argv[0]
    tag = "v" + version

    # Preconditions (untracked local files are fine; tracked changes are not)
    dirty = run_git("status", "--porcelain", "--untracked-files=no")
    if dirty:
        sys.exit("error: working tree has uncommitted changes, commit or stash them first.")
    if run_git("tag", "--list", tag):
        sys.exit(f"error: tag {tag} already exists.")

    short_hash = run_git("rev-parse", "--short", "HEAD")
    version_commit = f"{version}.{short_hash}"
    zip_url = ("https://github.com/freejishu/wordpress-mdx-next"
               f"/archive/refs/tags/{tag}.zip")

    # 1. style.css Version header
    style_css = REPO_ROOT / "style.css"
    text = style_css.read_text(encoding="utf-8")
    text, n = re.subn(r"^Version: .*$", f"Version: {version}", text, count=1, flags=re.M)
    if n != 1:
        sys.exit("error: 'Version:' header not found in style.css")
    style_css.write_text(text, encoding="utf-8")

    # 2. admin_init_ver.php (normally generated by the build tool; we regenerate it here)
    (REPO_ROOT / "includes" / "admin_init_ver.php").write_text(
        "<?php //此文件内容会由构建工具自动生成\n"
        f"if(get_option('mdx_version_commit')!='{version_commit}')"
        f"{{update_option('mdx_version', '{version}');"
        f"update_option('mdx_version_commit', '{version_commit}');}}?>",
        encoding="utf-8",
    )

    # 3. cdn_version.php (pin static-asset CDN to current HEAD)
    (REPO_ROOT / "includes" / "cdn_version.php").write_text(
        "<?php //This file will be generated automatically\n"
        f"$cdn_commit_version = '{short_hash}';\n"
        "?>",
        encoding="utf-8",
    )

    # 4. info.json
    info = {
        "version": version,
        "details_url": "https://github.com/freejishu/wordpress-mdx-next/releases",
        "download_url": zip_url,
    }
    (REPO_ROOT / "info.json").write_text(
        json.dumps(info, ensure_ascii=False, indent=4) + "\n", encoding="utf-8"
    )

    # 5. commit + tag
    run_git("add", "style.css", "includes/admin_init_ver.php",
            "includes/cdn_version.php", "info.json")
    run_git("commit", "-m", f"chore: release {tag}")
    run_git("tag", "-a", tag, "-m", f"release {tag}")
    print(f"done: {tag} (version_commit {version_commit}, cdn pin {short_hash})")

    # 6. optional push
    if do_push:
        run_git("push", "origin", "main")
        run_git("push", "origin", tag)
        print("pushed: origin main + " + tag)

        # 7. best-effort jsDelivr cache refresh for the update metadata.
        # Branch URLs are cached up to ~12h; purging usually speeds it up,
        # but full propagation can still take a while.
        import urllib.request
        purge_url = ("https://purge.jsdelivr.net/gh/freejishu/"
                     "wordpress-mdx-next@main/info.json")
        try:
            urllib.request.urlopen(purge_url, timeout=20).read()
            print("jsdelivr cache purge requested (info.json @main)")
        except Exception as exc:
            print(f"warn: jsdelivr purge failed ({exc}); "
                  "metadata will propagate within ~12h anyway")
    else:
        print("next: git push origin main && git push origin " + tag)


if __name__ == "__main__":
    main()
